name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up remote
        env:
          HF_TOKEN: ${{ secrets.HG }}
        run: git remote add space https://faalli:$HG@huggingface.co/spaces/faalli/demo

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HG }}
        run: git push --force https://faalli:$HG@huggingface.co/spaces/faalli/demo main
